### ISSUE TITLE
Biodiversity for the National Parks (IDA)

### ISSUE THREAD

**Issue by asadmehdi785** [msendik/intro-data-capstone-biodiversity#1]
### Criteria 1: Presentation: Are all required slides present?
* _Score Level:_  4
* _Comment(s):_ All the requirements are met in the analysis document.

### Criteria 2: Understanding hypothesis testing and interpreting the p-value
* _Score Level:_ 4
* _Comment(s):_ Hypothesis was formulated, hypothesis testing was done, and based on the results the hypothesis was accepted/rejected. The hypothesis outcome was interpreted correctly and connected to the objective of the analysis.
 
### Criteria 3: Ability to interpret the Objective & Outcome of the analysis in business context
* _Score Level:_ 4
* _Comment(s):_ Objective clearly states the reason for the analysis. Findings are interpreted accurately and are summarized in the recommendations.

 ### Overall Score: 12/12
Outstanding job with this project! I really liked your presentation and how cleanly everything was presented, it looked very professional. I also liked how you also made good use of charts and other graphics to show the data in an easy to comprehend manner.

Really excellent work. I hope you enjoyed the course!

**Comment by msendik** [comment]
Thank you very much for the feedback - I really enjoyed the course. I look forward to applying what I learned on future assignments at work!
